services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
      interval: 5s
      timeout: 5s
      retries: 10

  kafka-init:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      echo 'Waiting for Kafka to be ready...'
      sleep 15
      kafka-topics --create --if-not-exists --topic design.saved --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1
      kafka-topics --create --if-not-exists --topic validation.results --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1
      echo 'Topics created successfully'
      "

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sduser -d systemdesignboard"]
      interval: 3s
      timeout: 3s
      retries: 5

  backend-java:
    build: ./backend-java
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      FRONTEND_URL: http://localhost

  backend-node:
    build: ./backend-node
    ports:
      - "3000:3000"
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      backend-java:
        condition: service_started
    environment:
      PORT: 3000
      JAVA_API_URL: http://backend-java:8080
      FRONTEND_URL: http://localhost
      KAFKA_BROKER: kafka:29092
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      GROQ_API_KEY: ${GROQ_API_KEY}
      GROQ_MODEL: llama-3.3-70b-versatile
  
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend-node

volumes:
  pgdata: